# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file
ThemeName=AppTheme
ComponentsDir=shared/src/commonMain/kotlin/com/green/yp/app/components/generated
PackageName=com.green.yp.app.components.generated
KotlinMultiplatform=false 